project_id = "xfbxbbepvtwpuhuxtsyy"

[functions.test-mysql]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-signup]
verify_jwt = false

[functions.auth-logout]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.meetings-api]
verify_jwt = false

[functions.tags-api]
verify_jwt = false

[functions.meeting-tags-api]
verify_jwt = false

[functions.trigger-summary]
verify_jwt = false
