// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfbxbbepvtwpuhuxtsyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmYnhiYmVwdnR3cHVodXh0c3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTU5MjMsImV4cCI6MjA3MDkzMTkyM30.jGumVZosuUBG8lI7kspafTKGX_GGaVyjPTJbjwzgON4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});